version: "3.9"
name: sedma

services:
  backend:
    restart: always
    image: spv99build/sedma-server:latest
    environment:
      - VIRTUAL_HOST=api.sedma.spv99.com
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=api.sedma.spv99.com
      - CLIENT_APP_URL=https://sedma.spv99.com
    depends_on:
      - redis  
    networks:
      - sedma
      - proxy-net
    expose:
      - 3000

  frontend:
    restart: always
    image: spv99build/sedma-client:latest
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=sedma.spv99.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=sedma.spv99.com
      - NX_SERVER_API_URL=https://api.sedma.spv99.com
    expose:
      - 80
    networks:
      - proxy-net

  redis:
    restart: always
    image: redis:7
    networks:
      sedma:
        aliases:
          - redis

    expose:
      - 6379
    ports:
      - 6379:6379 # used only for debug purpose, not needed for anything else

networks:
  sedma:
  proxy-net:
    name: proxy-net
    external: true

