version: '3.9'
name: srv

services:
  proxy:
    container_name: proxy
    restart: always
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    environment:
      - TRUST_DOWNSTREAM_PROXY=false #true if there is another proxy in front of this one
    networks:
      - proxy-net

  acme:
    restart: always
    image: nginxproxy/acme-companion
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=admin@spv99.com #email to receive notifications from letsencrypt.org
      - NGINX_PROXY_CONTAINER=proxy #name of nginx-proxy container

  mongo:
    image: mongo:6.0.5
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    expose:
      - 27017
    ports:
      - 37017:27017 # used only for debug purpose, not needed for anything else
    networks:
      - mongo-net

networks:
  proxy-net:
    name: proxy-net
    external: true
  mongo-net:
    name: mongo-net
    external: true

volumes:
  certs:
  vhost:
  html:
  acme:      
  mongodata:
    driver: local
    driver_opts:
      type: ext4
      device: /dev/disk/by-id/scsi-0HC_Volume_100109400
